services:
  localstack-pagamento:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-pagamento}"
    image: localstack/localstack
    ports:
      - "4567:4566"            # LocalStack Gateway
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=dynamodb,sqs
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-aws:/etc/localstack/init/ready.d"

  app-pagamento:
    build:
      context: ..
      dockerfile: ./Dockerfile
    container_name: spring-boot-app-pagamento
    ports:
      - "8083:8080"
    depends_on:
      - localstack-pagamento
    networks:
      - backend

networks:
  backend: